server:
  port: 8031

spring:
  application:
    name: hystrix-turbine

eureka:
  client:
    service-url:
      defaultZone: http://user:123456@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
turbine:
  app-config: consumer-movie,consumer-ticket
  cluster-name-expression: "'default'"