server:
  port: 8050

eureka:
  client:
    service-url:
      defaultZone: http://user:123456@localhost:8761/eureka/
  instance:
    prefer-ip-address: true

spring:
  application:
    name: file-upload
  http:
    multipart:
      max-file-size: 2000Mb # default 1Mb
      max-request-size: 2500Mb # default 10Mb

# \u9488\u5BF9\u4E0A\u4F20\u5927\u6587\u4EF6\u8D85\u65F6\u7684\u5904\u7406
hystrix:
  command:
    default:
      execution:
        isotion:
          thread:
            timeoutInMilliseconds: 60000

ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000

# \u914D\u5408zuul\u505A\u6587\u4EF6\u4E0A\u4F20
# url:http://zuulServiceIp:port/zuul/file-upload/upload POST \u5927\u6587\u4EF6
# url:http://zuulServiceIp:port/file-upload/upload POST \u5C0F\u6587\u4EF6

# \u670D\u52A1\u81EA\u8EAB\u4E0A\u4F20
# url:http://localhost:port/upload POST \u5927\u5C0F\u6587\u4EF6
