eureka:
  client:
    healthcheck:
      enabled: true #将自身的健康状态发送给注册中心
    service-url:
      # defaultZone: http://localhost:8761/eureka/ #注册到不需要认证的注册中心
      defaultZone: http://user:123456@localhost:8761/eureka/ #注册到需要认证的注册中心
  instance:
    # 这里若是false，将会把os名字注册到注册中心，反之为ip
    prefer-ip-address: true
    metadata-map: {"name":"provider-user"}


spring:
  application:
    name: provider-user
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: h2
    schema: classpath:data/schema.sql
    data: classpath:data/data.sql
  profiles:
    active: user8000
logging:
  level:
    root: info
    org.hibernate: info
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.hibernate.type.descriptor.sql.BasicExtractor: trace



info:
  app:
    name: @project.artifactId@
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
      target: @java.version@

---
spring:
  profiles: user8000

server:
  port: 8000

---
spring:
  profiles: user8001
server:
  port: 8001
