spring:
  application:
    name: provider-user
  datasource:
    platform: h2
    data: classpath:data/data.sql
    schema: classpath:data/schema.sql
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  cloud:
    consul:
      discovery:
        health-check-interval: 15s
#        tags: foo=bar, baz
#        instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
server:
  port: 8000