spring:
  application:
    name: turbine
server:
  port: 8060
applications: consulhystrixclient
turbine:
#  aggregator:
#    cluster-config: ${applications}
  app-config: provider-user,consumer-movie
  cluster-name-expression: "'default'"
  combine-host-port: true