# \u5982\u679C\u4F7F\u7528spring cloud consul config\uFF0C\u4E0B\u9762\u8FD9\u6BB5\u4E3B\u673A\u53CA\u7AEF\u53E3\u7684\u914D\u7F6E\u9700\u8981\u653E\u5230bootstrap\u4E2D
spring:
  cloud:
    consul:
      discovery:
        health-check-interval: 15s
#        tags: foo=bar, baz
#        instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
  application:
    name: consumer-movie
server:
  port: 8010
