spring:
  application:
    name: discovery-eureka
  profiles:
    active: peer1
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0

security:
  basic:
    # \u5F00\u542F\u57FA\u4E8EHTTP basic \u7684\u8BA4\u8BC1
    enabled: true
  user:
    # \u767B\u5F55\u5E10\u53F7\uFF1A user 123456
    name: user
    password: 123456

info:
  app:
    name: @project.artifactId@
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
      target: @java.version@

# erueka \u81EA\u6211\u4FDD\u62A4\u6A21\u5F0F
eureka:
  server:
    enable-self-preservation: true

#\u5F53\u524DProfile\u6709 peer1\u3001peer2\uFF0C\u53EF\u4EE5java -jar xxx.jar spring.profiles.active=peer1/peer2 \u542F\u52A8\u4E24\u6B21\u8FBE\u6210eureka\u96C6\u7FA4
---
spring:
  # \u6307\u5B9A profile
  profiles: peer1

server:
  port: 8761

eureka:
  instance:
    # \u6307\u5B9A\u5F53profile=peer1\u65F6,\u4E3B\u673A\u540D\u662Fpeer1
    hostname: peer1
  client:
    # register-with-eureka: false
    # fetch-registry: false
    service-url:
      # \u5C06\u81EA\u5DF1\u6CE8\u518C\u5230peer2\u8FD9\u4E2AEureka\u4E0A
      #defaultZone: http://peer2:8761/eureka/              #\u6CE8\u518C\u5230\u4E0D\u9700\u8981\u8BA4\u8BC1\u7684\u6CE8\u518C\u4E2D\u5FC3
      defaultZone: http://user:123456@peer2:8761/eureka/   #\u6CE8\u518C\u5230\u9700\u8981\u8BA4\u8BC1\u7684\u6CE8\u518C\u4E2D\u5FC3

---
spring:
  profiles: peer2

server:
  port: 8762
eureka:
  instance:
    hostname: peer2
  client:
    service-url:
      defaultZone: http://user:123456@peer1:8761/eureka/